[package]
name = "dict_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-linux = "0.6"
lazy_static = "1.4"
toml = "0.7"
anyhow = "1"
serde = { version = "1", features = ["derive"] }